- name: "CommunityRepository"
  color: "D4C5F9"
- name: "package-cacher"
  color: "D4C5F9"
- name: "package-cleaner"
  color: "D4C5F9"
  aliases: ["package-cleanup"]
- name: "package-scanner"
  color: "D4C5F9"
- name: "package-validator"
  color: "D4C5F9"
- name: "package-verifier"
  color: "D4C5F9"
- name: "shimgen"
  color: "D4C5F9"